name: 'Report-link-action'
description: 'Action that reports incorrect in repository documentation eg. expired links as new issues.'
inputs:
  github_token:
    description: 'GitHub access token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'