on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Verify markdown links
      uses: ./
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'